language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
before_install:
  - "sudo  apt-get install pkg-config libxml2-dev libglib2.0-dev libncurses5-dev \
    python-yaml libevent-dev libpcre3-dev -y"
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("LibTrading")'
  - julia -e 'Pkg.test("LibTrading")'
